services:
    db_ums:
      image: postgres:17-alpine
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
#        test: "pg_isready -U ${DB_NAME} -h localhost"
        interval: 5s
        timeout: 5s
        retries: 20
        start_period: 10s
      container_name: psgr
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"



    ums_app:
      build: .
      command: >
        sh -c "alembic upgrade head &&
        uvicorn src.user_management_api.main:app --host 0.0.0.0 --port 8000"
      environment:
        - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@db_ums:5432/${DB_NAME}
      depends_on:
        db_ums:
          condition: service_healthy
      ports:
        - "8000:8000"

volumes:
  postgres-data: